---

- name: Deleting previous containers if found
  command: docker rm drupal drupaldb -f
  ignore_errors: yes

- name: Running the docker compose in detach mode
  command: docker-compose up -d
  async: 1000
  poll: 10
  args:
    chdir: "{{project_dir}}/{{project_folder_name}}"
